// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdgTGmWU8t1rVXriFlrwYDmRVx7Cn21Z0',
    appId: '1:550205446239:web:0c163e88f15dd7cc0823ea',
    messagingSenderId: '550205446239',
    projectId: 'myproductivityapp-94423',
    authDomain: 'myproductivityapp-94423.firebaseapp.com',
    storageBucket: 'myproductivityapp-94423.firebasestorage.app',
    measurementId: 'G-HWPP418W1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Sjya2UNfjc46_DPjS3CjtG33LlNB_fY',
    appId: '1:550205446239:android:d5044c891cd93b9a0823ea',
    messagingSenderId: '550205446239',
    projectId: 'myproductivityapp-94423',
    storageBucket: 'myproductivityapp-94423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmhdMEp-FsjSpFiq-naZwlBzmj0hYDrOM',
    appId: '1:550205446239:ios:2aad45d22f3533380823ea',
    messagingSenderId: '550205446239',
    projectId: 'myproductivityapp-94423',
    storageBucket: 'myproductivityapp-94423.firebasestorage.app',
    iosBundleId: 'com.example.myProductivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmhdMEp-FsjSpFiq-naZwlBzmj0hYDrOM',
    appId: '1:550205446239:ios:2aad45d22f3533380823ea',
    messagingSenderId: '550205446239',
    projectId: 'myproductivityapp-94423',
    storageBucket: 'myproductivityapp-94423.firebasestorage.app',
    iosBundleId: 'com.example.myProductivityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdgTGmWU8t1rVXriFlrwYDmRVx7Cn21Z0',
    appId: '1:550205446239:web:e25eba2aaaea41160823ea',
    messagingSenderId: '550205446239',
    projectId: 'myproductivityapp-94423',
    authDomain: 'myproductivityapp-94423.firebaseapp.com',
    storageBucket: 'myproductivityapp-94423.firebasestorage.app',
    measurementId: 'G-EHV7ED1DT6',
  );
}
